package com.gaitdetector

import android.content.Context
import org.json.JSONObject
import org.tensorflow.lite.Interpreter
import java.io.FileInputStream
import java.nio.MappedByteBuffer
import java.nio.channels.FileChannel
import kotlin.math.sqrt

/**
 * Wraps the TFLite encoder model (input layer → bottleneck only).
 *
 * Usage:
 *   val embedding = autoencoder.getEmbedding(features)  // FloatArray[12]
 *   val dist      = GaitAutoencoder.l2(embedding, template)
 *
 * Asset required: gait_encoder.tflite  (generated by train_autoencoder.py)
 * Asset required: scaler_params.json   (generated by train_autoencoder.py)
 */
class GaitAutoencoder(context: Context) {

    private val interpreter: Interpreter
    private val scalerMean: FloatArray
    private val scalerStd:  FloatArray
    val embeddingDim: Int
    val suggestedBaseThreshold: Float

    init {
        interpreter = Interpreter(loadModelFile(context))

        val json     = JSONObject(
            context.assets.open("scaler_params.json").bufferedReader().readText()
        )
        val meanArr  = json.getJSONArray("mean")
        val stdArr   = json.getJSONArray("std")
        scalerMean   = FloatArray(meanArr.length()) { meanArr.getDouble(it).toFloat() }
        scalerStd    = FloatArray(stdArr.length())  { stdArr.getDouble(it).toFloat() }

        embeddingDim            = interpreter.getOutputTensor(0).shape()[1]
        suggestedBaseThreshold  = json.optDouble("suggested_threshold", 1.0).toFloat()
    }

    /**
     * Normalises the raw feature vector and runs it through the encoder.
     * Returns the bottleneck embedding (FloatArray of size embeddingDim).
     */
    fun getEmbedding(features: FloatArray): FloatArray {
        require(features.size == GaitFeatureExtractor.NUM_FEATURES)
        val normalised   = FloatArray(features.size) {
            (features[it] - scalerMean[it]) / scalerStd[it]
        }
        val inputBuf     = Array(1) { normalised }
        val outputBuf    = Array(1) { FloatArray(embeddingDim) }
        interpreter.run(inputBuf, outputBuf)
        return outputBuf[0]
    }

    fun close() = interpreter.close()

    // ── Static helpers ────────────────────────────────────────────────────────

    companion object {
        /** Euclidean (L2) distance between two equal-length vectors. */
        fun l2(a: FloatArray, b: FloatArray): Float {
            require(a.size == b.size)
            var sum = 0.0
            for (i in a.indices) {
                val d = (a[i] - b[i]).toDouble()
                sum += d * d
            }
            return sqrt(sum).toFloat()
        }
    }

    // ── Asset loading ─────────────────────────────────────────────────────────

    private fun loadModelFile(context: Context): MappedByteBuffer {
        val fd = context.assets.openFd("gait_encoder.tflite")
        return FileInputStream(fd.fileDescriptor).channel.map(
            FileChannel.MapMode.READ_ONLY, fd.startOffset, fd.declaredLength
        )
    }
}
